name: DashURL CI

on:
  push:
    branches:
      - master

jobs:
  docker-compose-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Build Services
        run: docker compose build

      - name: Start Services
        run: docker compose up -d

      - name: Wait for Containers
        run: sleep 30

      - name: Check Running Containers
        run: docker compose ps

      - name: Show Logs
        run: docker compose logs

      - name: Cleanup
        if: always()
        run: docker compose down
